### ISSUE TITLE
Project requires Xcode 8.0 to run

### ISSUE THREAD

**Issue by jellybeanjohnny** [learn-co-curriculum/swift-arrayChallengeToo-lab#3]
I'm not able to run this project on Xcode 7.3.1. I get the below error:
<img width="258" alt="screen shot 2016-07-07 at 10 47 35 am" src="https://cloud.githubusercontent.com/assets/6811982/16657388/566722be-4430-11e6-8403-0a8e92717629.png">

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by JimCampagno** [comment]
This has been fixed. Thanks @jellybeanjohnny - I appreciate you raising these issues.
